name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy, rustfmt
      - name: test
        run: cargo test --verbose
      - name: lint
        run: cargo clippy --lib --bin arkavo --all-features -- -D warnings
      - name: format
        run: cargo fmt --all --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          strip target/x86_64-unknown-linux-gnu/release/arkavo
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu-build
          path: target/x86_64-unknown-linux-gnu/release/arkavo

  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Run benchmark
        run: |
          cargo bench | tee criterion_output.txt
          grep "time:" criterion_output.txt | sed -E 's/time:.*\[([0-9.]+) ([a-z]+) ([0-9.]+) ([a-z]+) ([0-9.]+) ([a-z]+)\]/\1,\3,\5/' > output.txt
          pwd
          ls -l
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: output.txt
          fail-on-alert: false
